# Generated by Django 3.2.16 on 2022-11-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcategory',
            name='hierarchy',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
